content = open('E:/thalium/src/roles/triage.ts', encoding='utf-8').read()

old = "return `Classify this input against the 11 intent types and return ONLY a JSON object with these exact properties:\n- intent_type: one of ${validIntentTypes.join(', ')}\n- scope: one of ${validScopes.join(', ')}\n- domain: \"${domain}\"\n- specificity: 'general' unless the input clearly indicates a more specific pattern\n- classification_confidence: between 0 and 1\n- classification_rationale: brief explanation\n- active_roles: array based on intent type\n- urgency: 'acute' only for diagnosis inputs with production impact language\n- prior_baseline_detected: true only for change_request inputs\n\nInput: ${input}\n\nReturn ONLY the JSON object with no markdown, no explanation, no other formatting.`;"

new = "return `Classify this input against the 11 intent types and return ONLY a JSON object with these exact properties:\n- intent_type: one of ${validIntentTypes.join(', ')}\n- scope: one of ${validScopes.join(', ')}\n- domain: \"${domain}\"\n- specificity: 'general' unless the input clearly indicates a more specific pattern\n- classification_confidence: between 0 and 1\n- classification_rationale: brief explanation\n- active_roles: array based on intent type\n- urgency: 'acute' only for diagnosis inputs with production impact language\n- prior_baseline_detected: true only for change_request inputs\n\nCRITICAL CLASSIFICATION RULES:\n1. specification vs planning: 'Build X', 'Create X', 'Design X' with no prior baseline = specification. planning is only when the requester's own team self-executes with no external handoff.\n2. change_request requires a prior baseline. 'Build X from scratch' = specification. 'Add X to existing Y' = change_request.\n3. scope: project = specific bounded engagement. org = organisation-wide. entity = specific named system or component. global = external knowledge ingestion only.\n4. diagnosis requires an active problem: broken, failing, error, down. No active problem = not diagnosis.\n5. verification requires evidence: PR links, test results, done, complete, ready to ship.\n\nEXAMPLES:\n- 'Build a SaaS marketplace' -> specification, project\n- 'Add feature to existing app' -> change_request, project\n- 'Payments service throwing 503 errors' -> diagnosis, entity\n- 'Q3 tech debt review' -> retrospective, org\n- 'What did we decide about rate limits?' -> knowledge_retrieval, entity\n\nInput: ${input}\n\nReturn ONLY the JSON object with no markdown, no explanation, no other formatting.`;"

if old in content:
    open('E:/thalium/src/roles/triage.ts', 'w', encoding='utf-8').write(content.replace(old, new))
    print('REPLACED OK')
else:
    print('NOT FOUND')
